name: Generate Posts

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:     # allows manual trigger

jobs:
  trigger-generator:
    runs-on: ubuntu-latest
    steps:
      - name: Debug token
        run: |
          echo "Token starts with: ${INTERNAL_API_TOKEN:0:8}"
        env:
          INTERNAL_API_TOKEN: ${{ secrets.INTERNAL_API_TOKEN }}