name: Generate and Publish Posts

on:
  schedule:
    - cron: '0 */6 * * *'   # runs every 6 hours
  workflow_dispatch:      # allows manual trigger

jobs:
  run_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Post Generation
        run: |
          echo "Calling generator endpoint..."
          curl -X GET "${{ secrets.GENERATOR_URL }}" \
            -H "x-internal-token: ${{ secrets.INTERNAL_API_TOKEN }}"

      - name: Wait for database to commit
        run: sleep 60 # Waits 60 seconds to ensure posts are saved before publishing

      - name: Trigger Post Publishing
        run: |
          echo "Calling publish endpoint..."
          curl -X POST "${{ secrets.PUBLISH_URL }}" \
            -H "x-internal-token: ${{ secrets.INTERNAL_API_TOKEN }}"
