name: Generate Posts

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:     # allows manual trigger

jobs:
  trigger-generator:
    runs-on: ubuntu-latest
    steps:
      - name: Call generator endpoint
        run: |
          curl -X GET "$GENERATOR_URL" \
            -H "x-internal-token: $INTERNAL_API_TOKEN"
        env:
          GENERATOR_URL: https://your-vercel-app.vercel.app/api/posts/generate
          INTERNAL_API_TOKEN: ${{ secrets.INTERNAL_API_TOKEN }}
