name: Publish Posts

on:
  workflow_run:
    workflows:
      - Generate Posts           # must exactly match the name above
    types:
      - completed

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Wait for DB commit
        run: sleep 10

      - name: Trigger publish endpoint
        env:
          DEPLOY_URL: ${{ secrets.DEPLOY_URL }}
          INTERNAL_API_TOKEN: ${{ secrets.INTERNAL_API_TOKEN }}
        run: |
          echo "Calling publish endpoint at $DEPLOY_URL/api/posts/publish ..."
          RESPONSE=$(curl -s -X POST "$DEPLOY_URL/api/posts/publish" \
            -H "x-internal-token: $INTERNAL_API_TOKEN" \
            -H "Content-Type: application/json")

          echo "Response:"
          echo "$RESPONSE"

          if echo "$RESPONSE" | grep -q '"success":false'; then
            echo "⚠️  One or more posts failed to publish"
            exit 1
          fi